baseURL = 'http://example.org/'
languageCode = 'en-us'
title =  ' minyong.write();'
theme = 'hugo-book'
[params]
 # BookTheme = 'dark'
  BookMenuBundle = '/menu'
  BookLogo = 'logo.png'
  BookRepo = 'https://github.com/min-96/minyong_info'
  BookEditPath = 'edit/master/'
